### ISSUE TITLE
Please merge AFNI Interfaces into Nipype upstream

### ISSUE THREAD

**Issue by chrisgorgo** [PIRCImagingTools/sfDM#1]
Congrats on the paper. I added sfDM to featured software on Nipype website: https://github.com/nipy/nipype/pull/1056

Could you merge the AFNI Interfaces you developed back to Nipype upstream? A Pull Request would be great.

**Comment by rafaceschin** [comment]
Thank you!
Sorry for the delay. Just finished my comprehensive exams so I got swamped for a while.
Will do it right away.
